apiVersion: apps/v1
kind: Deployment # Specifies that this resource is a Deployment, managing a set of replica Pods.
metadata:
  name: murphy-auth # Names this Deployment as "murphy-auth".
spec:
  replicas: 1 # Indicates that one replica (pod) of the application should be running.
  selector:
    matchLabels:
      app: murphy-auth # The selector specifies that this Deployment targets pods labeled "app: murphy-auth".
  template:
    metadata:
      labels:
        app: murphy-auth # Labels the Pods with "app: murphy-auth" to match the selector above.
    spec:
      containers:
        - name: murphy-auth-container # Names the container within the Pod as "murphy-auth-container".
          image: nickfang1996/cs122b-p5-murphy-login:v2 # Uses the same Docker image as murphy-movies.
          ports:
            - name: http
              containerPort: 8080 # Exposes port 8080 of the container.
          resources:
            limits:
              cpu: "1"    # Limits the container to use at most 1 CPU.
              memory: "1Gi" # Limits the container to use at most 1 GiB of memory.
      imagePullSecrets: # Specifies the secret(s) for pulling private images from DockerHub.
        - name: regcred # References the Kubernetes secret named "regcred".
---
apiVersion: v1
kind: Service # Specifies that this resource is a Service, defining how to access the Pods.
metadata:
  name: murphy-auth-service # Names this Service as "murphy-auth-service".
spec:
  selector:
    app: murphy-auth # Selects the Pods labeled "app: murphy-auth".
  ports:
    - name: http
      port: 8080 # Exposes the service on port 8080 internally in the cluster.
  type: ClusterIP # Makes the service only accessible within the cluster.
